[build-system]
requires = ["setuptools>=56", "wheel", "setuptools_scm[toml]>=3.4.1"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.black]
skip-string-normalization = true

[tool.setuptools_scm]

[pytest.enabler.mypy]
addopts = "--mypy"

[pytest.enabler.cov]
addopts = "--cov"
